<?php

namespace App\Tests\Cart;

use App\Shop\Application\services\Cart\AddToCartService;
use App\Shop\Domain\Cart\CartRepository;
use App\Shop\Domain\Exceptions\CartExceptions;
use App\Shop\Domain\Exceptions\PriceExceptions;
use App\Shop\Domain\Product\Price;
use App\Shop\Domain\Product\Product;
use App\Shop\Domain\Product\ProductRepository;
use App\Shop\Domain\User\EmailVO;
use App\Shop\Domain\User\PassVO;
use App\Shop\Domain\User\User;
use App\Shop\Domain\User\UserRepository;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class AddToCartTest extends TestCase
{
    private MockObject|CartRepository $cr;

    private MockObject|ProductRepository $pr;

    private AddToCartService $addToCartService;

    public function __construct(string $name)
    {
        parent::__construct($name);
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ur = $this->getMockBuilder(UserRepository::class)->disableOriginalConstructor()->getMock();
        $this->cr = $this->getMockBuilder(CartRepository::class)->disableOriginalConstructor()->getMock();
        $this->pr = $this->getMockBuilder(ProductRepository::class)->disableOriginalConstructor()->getMock();
        $this->addToCartService = new  AddToCartService($this->ur, $this->pr, $this->cr);

    }


    /**
     * @throws PriceExceptions
     * @throws CartExceptions
     */
    public function testSave()
    {
        // Configurar los mock objects
        $user = new User('Jose', new EmailVO("diego81@gmail.com"), new PassVO("1234567aA"));
        $user->setId(1);
        $product = new Product('gafas', 150, new Price(15.99, 'EUR'));
        $product->setId(1);

        $this->ur->expects($this->once())
            ->method('findById')
            ->with($this->equalTo(1))
            ->willReturn($user);


        $this->pr->expects($this->once())
            ->method('findById')
            ->with($this->equalTo(2))
            ->willReturn($product);
        $this->addToCartService->addToCart(1, 2, 3);
        $this->assertTrue(true);

    }

}